key_folder = "./psk/bob"
qupskd_bind = "localhost"
qupskd_port = 5556
enable_fake_qkd_api = true
etsi_url = "http://localhost:5556"
remote_qupskd_url = "http://localhost:5555"
alias = "bob"
psk = "thisisverysecret"
source_KME_ID = "hsn_bob"
target_KME_ID = "hsn_alice"
master_SAE_ID = "sae_bob"
remote_SAE_ID = "sae_alice"
