key_rotation_seconds = 120
key_folder = "./psk/carol"

qupskd_bind = "localhost"
qupskd_port = 5557

enable_fake_qkd_api = true

[peers]

[peers.hsn_bob]
etsi_url = "http://localhost:5557"
qupskd_url = "http://localhost:5556"

alias = "bob"

psk = "donttellalice"

source_KME_ID = "hsn_carol"

master_SAE_ID = "sae_carol"
remote_SAE_ID = "sae_bob"
