
qupskd_bind = "localhost" # Interface/IP for qupskd binding
qupskd_port = 5555        # Port for qupskd service

# For those without access to an expensive QKD setup, qupskd can simulate a QKD
# device. This mode generates keys based on the key_ID hash, making them
# available on both ends but completely insecure.
enable_fake_qkd_api = true

etsi_url = "http://localhost:5555"          # QKD device for key requests
remote_qupskd_url = "http://localhost:5556" # Peer qupskd address

# If you want to store the PSK in a file
key_folder = "./psk/alice" # (optional) Directory for storing generated keys
alias = "bob"              # Name for storing the key
psk = "thisisverysecret"   # (optional) Extra PSK to add to the mix

# If you want to inject the PSK directly into WireGuard
# wg-set-psk is required, see https://github.com/aparcar/wg-set-psk
#
# wireguard_public_key = "GOJt/mfPuwoUiKD+hARpxuDtnzJOWkcK0Tq+sxxw4UQ="

source_KME_ID = "hsn_alice" # Identifier for the "Key Management Entity" in operation
target_KME_ID = "hsn_bob"   # Identifier for the "Key Management Entity" intended for communication
master_SAE_ID = "sae_alice" # Identifier for the "Secure Application Entity" in operation
remote_SAE_ID = "sae_bob"   # Identifier for the "SAE" intended for communication
