key_rotation_seconds = 120
key_folder = "./psk/bob"

ukms_bind = "localhost"
ukms_port = 5556

enable_fake_qkd_api = true

[peers]

[peers.hsn_alice]
etsi_url = "http://localhost:5556"
ukms_url = "http://localhost:5555"

alias = "alice"

source_KME_ID = "hsn_bob"

master_SAE_ID = "sae_bob"
remote_SAE_ID = "sae_alice"

[peers.hsn_carol]
etsi_url = "http://localhost:5556"
ukms_url = "http://localhost:5557"

alias = "carol"

source_KME_ID = "hsn_bob"

master_SAE_ID = "sae_bob"
remote_SAE_ID = "sae_carol"
