key_rotation_seconds = 120
key_folder = "./psk/alice"

ukms_bind = "localhost"
ukms_port = 5555

enable_fake_qkd_api = true

[peers]

[peers.hsn_bob]
etsi_url = "http://localhost:5555"
ukms_url = "http://localhost:5556"

alias = "bob"

source_KME_ID = "hsn_alice"

master_SAE_ID = "sae_alice"
slave_SAE_ID = "sae_bob"
